# This is a basic workflow to help you get started with Actions

name: Deploy to Alibaba Cloud ECI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
 
      # Runs a single command using the runners shell
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Alibaba Cloud Container Registry
        run: |
          docker login --username=${{ secrets.ACR_USERNAME }} --password=${{ secrets.ACR_PASSWORD }} ${{ secrets.ACR_REGISTRY }}
     
      - name: Build and Push Docker Image
        run: |
          ls -la
          IMAGE_TAG=$(git rev-parse --short HEAD)-$(date +%Y%m%d%H%M%S)
          IMAGE_NAME=registry-intl.ap-northeast-1.aliyuncs.com/kang-tokyo/warehouse-tokyo:$IMAGE_TAG 

          docker build -t "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"
          
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
    
  deploy-to-eci:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install Alibaba Cloud CLI
        run: |
          curl -L https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz | tar -xz
          sudo mv aliyun /usr/local/bin/

      - name: Configure Alibaba Cloud CLI
        run: |
          aliyun configure set --access-key-id LTAI5t8BEPhcLT5BkW9tkQja \
                              --access-key-secret TKKPPbYQu1W6I9S76YmqTsnf3Hg6rn \
                              --region ap-northeast-1

      - name: Deploy to Alibaba Cloud ECI
        run: |
          aliyun eci DeleteContainerGroup --RegionId ap-northeast-1 --ContainerGroupId eci-6wedk7gyui7r0hy1x4b1 || true

          aliyun eci CreateContainerGroup \
            --RegionId ap-northeast-1 \
            --ContainerGroupName container-group-1742216801098 \
            --Container.1.Image registry-intl.ap-northeast-1.aliyuncs.com/kang-tokyo/warehouse-tokyo:${{ env.IMAGE_TAG }} \
            --Container.1.Name my-app-container \
            --Container.1.Cpu 1 \
            --Container.1.Memory 2 \
            --VSwitchId vsw-6wedckw8ivhipmmmfbb33 \
            --SecurityGroupId sg-6we5yo89xyhf9zuhetmt
